version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "dev"
    commit-message:
      prefix: "chore(deps):"
    groups:
      dev-dependencies:
        patterns:
          - "ruff"
          - "mypy"
          - "pytest"
          - "pytest-*"
          - "pre-commit"
      docs-dependencies:
        patterns:
          - "mkdocs*"
          - "pymdown-extensions"
