@echo off
setlocal enabledelayedexpansion

REM pyKorf Distribution Script
REM Obfuscates Python source with PyArmor and packages for distribution

set DIST_DIR=dist
set PACKAGE_NAME=pykorf
set TRIAL_DAYS=5

REM Get version from pyproject.toml (match only ^version = to avoid requires-python)
for /f "tokens=3 delims= " %%v in ('findstr /r /c:"^version = " pyproject.toml') do set VERSION=%%v
set VERSION=%VERSION:"=%

echo === pyKorf Distribution Build ===
echo Version: %VERSION%
echo.

REM Clean previous builds
if exist %DIST_DIR% rd /s /q %DIST_DIR%
mkdir %DIST_DIR%

REM Step 1: Check PyArmor installation
echo Checking PyArmor installation...
uv run python -c "import pyarmor" 2>nul
if errorlevel 1 (
    echo Installing PyArmor...
    uv add pyarmor
)

REM Step 2: Obfuscate pykorf package with runtime inside package (-i)
echo.
echo Obfuscating pykorf package...
uv run pyarmor gen -O %DIST_DIR% -r -i -e %TRIAL_DAYS% ^
    --exclude "library/*" ^
    --exclude "config/*" ^
    --exclude "trail_files/*" ^
    --exclude "*.kdf" ^
    --exclude "*.lib" ^
    --exclude "*.csv" ^
    --exclude "*.txt" ^
    --exclude "*.pdf" ^
    --exclude "*.log" ^
    --exclude "*.json" ^
    pykorf

if errorlevel 1 (
    echo ERROR: PyArmor obfuscation failed
    exit /b 1
)

REM Generate static _version.py for distribution with dynamic version parsing
echo.
echo Generating static version file...
uv run python -c "import re; v='%VERSION%'; m=re.match(r'(\d+)\.(\d+)\.(\d+)',v); major,minor,patch=map(int,m.groups()) if m else (0,1,0); open(r'%DIST_DIR%\pykorf\_version.py','w').write(f'# file generated by distribute.bat\n# do not edit\n\n__version__ = version = \"{v}\"\n__version_tuple__ = version_tuple = ({major}, {minor}, {patch})\n__commit_id__ = commit_id = None\n')"

REM Create __main__.py for module execution
echo.
echo Creating __main__.py for module execution...
echo from pykorf.cli import main; main() > %DIST_DIR%\pykorf\__main__.py

REM Step 3: Copy non-Python files
echo.
echo Copying data files...

REM Copy only New.kdf from library directory (exclude all other files including fluids.txt)
if exist pykorf\library\New.kdf (
    mkdir %DIST_DIR%\pykorf\library
    copy /y pykorf\library\New.kdf %DIST_DIR%\pykorf\library\
)

REM Copy py.typed for type hints
if exist pykorf\py.typed (
    copy /y pykorf\py.typed %DIST_DIR%\pykorf\
)

REM Copy pyproject.toml and strip dev dependencies (only keep runtime deps)
echo.
echo Preparing pyproject.toml (stripping dev dependencies)...
uv run python -c "import re; c=open('pyproject.toml','r').read(); c=re.sub(r'\n\[tool\.uv\].*?(?=\n\[)','',c,flags=re.DOTALL); c=re.sub(r'\n\[dependency-groups\].*?(?=\n\[)','',c,flags=re.DOTALL); open('dist/pyproject.toml','w').write(c)"

REM Copy full launcher and add --trial flag for distribution
echo.
echo Preparing launcher...
copy /y pykorf.bat %DIST_DIR%\pykorf.bat >nul
uv run python -c "c=open(r'%DIST_DIR%\pykorf.bat','r').read(); c=c.replace('python -m pykorf','python -m pykorf --trial'); open(r'%DIST_DIR%\pykorf.bat','w').write(c)"

REM Step 4: Create distribution zip with version suffix (trial)
echo.
echo Creating distribution package...
uv run python -c "import zipfile, os; z = zipfile.ZipFile(r'%DIST_DIR%/%PACKAGE_NAME%-%VERSION%-trial.zip', 'w', zipfile.ZIP_DEFLATED); base = r'%DIST_DIR%'; [z.write(os.path.join(root, f), os.path.relpath(os.path.join(root, f), base)) for root, dirs, files in os.walk(base) for f in files if not f.endswith('.zip')]; z.close()"

REM Clean up unzipped content (keep only the zip)
echo Cleaning up...
for /d %%d in (%DIST_DIR%\*) do rd /s /q "%%d"
del /q %DIST_DIR%\pyproject.toml 2>nul

echo.
echo === Build Complete ===
echo Distribution package: %DIST_DIR%\%PACKAGE_NAME%-%VERSION%-trial.zip
echo.
echo Contents:
echo   - pykorf/          (obfuscated package)
echo   - pyproject.toml   (dependencies)
echo   - pykorf.bat       (launcher)
echo.
echo Extract and run pykorf.bat to launch the TUI.