@echo off
setlocal enabledelayedexpansion

REM pyKorf Distribution Script
REM Obfuscates Python source with PyArmor and packages for distribution

set DIST_DIR=dist
set PACKAGE_NAME=pykorf

REM Get version from pyproject.toml
for /f "tokens=3 delims= " %%v in ('findstr /c:"version = " pyproject.toml') do set VERSION=%%v
set VERSION=%VERSION:"=%

echo === pyKorf Distribution Build ===
echo Version: %VERSION%
echo.

REM Clean previous builds
if exist %DIST_DIR% rd /s /q %DIST_DIR%
mkdir %DIST_DIR%

REM Step 1: Check PyArmor installation
echo Checking PyArmor installation...
uv run python -c "import pyarmor" 2>nul
if errorlevel 1 (
    echo Installing PyArmor...
    uv add pyarmor
)

REM Step 2: Obfuscate pykorf package with runtime inside package (-i)
echo.
echo Obfuscating pykorf package...
uv run pyarmor gen -O %DIST_DIR% -r -i ^
    --exclude "library/*" ^
    --exclude "config/*" ^
    --exclude "trail_files/*" ^
    --exclude "*.kdf" ^
    --exclude "*.lib" ^
    --exclude "*.csv" ^
    --exclude "*.txt" ^
    --exclude "*.pdf" ^
    --exclude "*.log" ^
    --exclude "*.json" ^
    pykorf

if errorlevel 1 (
    echo ERROR: PyArmor obfuscation failed
    exit /b 1
)

REM Generate static _version.py for distribution
echo.
echo Generating static version file...
uv run python -c "open(r'%DIST_DIR%\pykorf\_version.py', 'w').write('# file generated by setuptools-scm\n# do not edit\n\n__version__ = version = \"0.1.0\"\n__version_tuple__ = version_tuple = (0, 1, 0)\n__commit_id__ = commit_id = None\n')"

REM Create __main__.py for module execution
echo.
echo Creating __main__.py for module execution...
echo from pykorf.cli import main; main() > %DIST_DIR%\pykorf\__main__.py

REM Step 3: Copy non-Python files
echo.
echo Copying data files...

REM Copy library directory (data files only)
if exist pykorf\library (
    mkdir %DIST_DIR%\pykorf\library
    xcopy /y pykorf\library\*.kdf %DIST_DIR%\pykorf\library\ 2>nul
    xcopy /y pykorf\library\*.lib %DIST_DIR%\pykorf\library\ 2>nul
    xcopy /y pykorf\library\*.csv %DIST_DIR%\pykorf\library\ 2>nul
    xcopy /y pykorf\library\*.txt %DIST_DIR%\pykorf\library\ 2>nul
    xcopy /y pykorf\library\*.pdf %DIST_DIR%\pykorf\library\ 2>nul
)

REM Copy trail_files directory (data files only)
if exist pykorf\trail_files (
    mkdir %DIST_DIR%\pykorf\trail_files
    xcopy /y pykorf\trail_files\*.kdf %DIST_DIR%\pykorf\trail_files\ 2>nul
)

REM Copy py.typed for type hints
if exist pykorf\py.typed (
    copy /y pykorf\py.typed %DIST_DIR%\pykorf\
)

REM Copy pyproject.toml and strip dev dependencies (only keep runtime deps)
echo.
echo Preparing pyproject.toml (stripping dev dependencies)...
uv run python -c "import re; c=open('pyproject.toml','r').read(); c=re.sub(r'\n\[tool\.uv\].*?(?=\n\[)','',c,flags=re.DOTALL); c=re.sub(r'\n\[dependency-groups\].*?(?=\n\[)','',c,flags=re.DOTALL); open('dist/pyproject.toml','w').write(c)"

REM Copy launcher batch script
echo.
echo Creating launcher...
copy /y pykorf.bat %DIST_DIR%\

REM Launcher already set up correctly from source pykorf.bat

REM Step 4: Create distribution zip with version suffix (trial)
echo.
echo Creating distribution package...
uv run python -c "import zipfile, os; z = zipfile.ZipFile(r'%DIST_DIR%/%PACKAGE_NAME%-%VERSION%-trial.zip', 'w', zipfile.ZIP_DEFLATED); base = r'%DIST_DIR%'; [z.write(os.path.join(root, f), os.path.relpath(os.path.join(root, f), base)) for root, dirs, files in os.walk(base) for f in files if not f.endswith('.zip')]; z.close()"

echo.
echo === Build Complete ===
echo Distribution package: %DIST_DIR%\%PACKAGE_NAME%-%VERSION%-trial.zip
echo.
echo Contents:
echo   - pykorf/          (obfuscated package)
echo   - pyproject.toml   (dependencies)
echo   - pykorf.bat       (launcher)
echo.
echo Extract and run pykorf.bat to launch the TUI.