@echo off
setlocal enabledelayedexpansion

REM pyKorf Distribution Script
REM Builds Vue frontend, copies Python source, and packages for distribution

set DIST_DIR=dist
set PACKAGE_NAME=pykorf

REM Get version from pyproject.toml (match only ^version = to avoid requires-python)
for /f "tokens=3 delims= " %%v in ('findstr /r /c:"^version = " pyproject.toml') do set VERSION=%%v
set VERSION=%VERSION:"=%

echo === pyKorf Distribution Build ===
echo Version: %VERSION%
echo.

REM Clean previous builds
if exist %DIST_DIR% rd /s /q %DIST_DIR%
mkdir %DIST_DIR%

REM Step 0: Build Vue frontend
echo ==========================================
echo Step 0: Building Vue frontend...
echo ==========================================
echo.
cd pykorf\app\frontend
call npm install 2>nul
if errorlevel 1 (
    echo ERROR: npm install failed — ensure Node.js is installed
    cd ..\..\..
    exit /b 1
)
call npm run build
if errorlevel 1 (
    echo ERROR: Vue frontend build failed
    cd ..\..\..
    exit /b 1
)
cd ..\..\..
echo.
echo Frontend build complete.
echo.

REM Step 1: Copy pykorf package directly (no obfuscation)
echo.
echo ==========================================
echo Step 1: Copying pykorf package...
echo ==========================================
echo.
robocopy "pykorf" "%DIST_DIR%\pykorf" /E /NFL /NDL /NJH /NJS ^
    /XD "library" ^
    /XD "node_modules" ^
    /XD "dist" ^
    /XD "src" ^
    /XD "__pycache__" ^
    /XF "*.kdf" ^
    /XF "*.lib" ^
    /XF "*.csv" ^
    /XF "*.txt" ^
    /XF "*.pdf" ^
    /XF "*.log" ^
    /XF "*.json"

if errorlevel 8 (
    echo ERROR: Failed to copy pykorf package
    exit /b 1
)

REM Copy Vue frontend build output
echo.
echo ==========================================
echo Step 1b: Copying Vue frontend assets...
echo ==========================================
echo.
if exist "pykorf\app\frontend\dist" (
    robocopy "pykorf\app\frontend\dist" "%DIST_DIR%\pykorf\app\frontend\dist" /E /NFL /NDL /NJH /NJS >nul 2>&1
    echo Copied Vue build output.
) else (
    echo WARNING: Vue dist not found — frontend will not be available.
)

REM Generate static _version.py for distribution with dynamic version parsing
echo.
echo ==========================================
echo Step 2: Generating _version.py...
echo ==========================================
echo.

REM Create _version.py using Python (generates tuple dynamically)
echo # file generated by distribute.bat>%DIST_DIR%\pykorf\_version.py
echo # do not edit>>%DIST_DIR%\pykorf\_version.py
echo.>>%DIST_DIR%\pykorf\_version.py
echo __version__ = version = "%VERSION%">>%DIST_DIR%\pykorf\_version.py
uv run python -c "v='%VERSION%';parts=v.split('.');print(f'__version_tuple__ = version_tuple = ({parts[0]}, {parts[1]}, {parts[2]})')">>%DIST_DIR%\pykorf\_version.py
echo __commit_id__ = commit_id = None>>%DIST_DIR%\pykorf\_version.py

REM Verify _version.py was created
echo Verifying _version.py...
if exist "%DIST_DIR%\pykorf\_version.py" (
    type "%DIST_DIR%\pykorf\_version.py"
) else (
    echo ERROR: _version.py was not created!
    exit /b 1
)

REM Step 3: Copy non-Python data files
echo.
echo ==========================================
echo Step 3: Copying data files...
echo ==========================================
echo.

REM Copy only New.kdf from library directory
if exist pykorf\library\New.kdf (
    mkdir %DIST_DIR%\pykorf\library 2>nul
    copy /y pykorf\library\New.kdf %DIST_DIR%\pykorf\library\ >nul
    echo   Copied New.kdf
)

REM Copy py.typed for type hints
if exist pykorf\py.typed (
    copy /y pykorf\py.typed %DIST_DIR%\pykorf\ >nul
    echo   Copied py.typed
)

REM Copy project_defaults.toml from app directory (required for smart defaults)
if exist pykorf\app\project_defaults.toml (
    copy /y pykorf\app\project_defaults.toml %DIST_DIR%\pykorf\app\ >nul
    echo   Copied project_defaults.toml
)

REM Copy sizing criteria TOML files from core/reports directory
if exist pykorf\core\reports\*.toml (
    mkdir %DIST_DIR%\pykorf\core\reports 2>nul
    copy /y pykorf\core\reports\*.toml %DIST_DIR%\pykorf\core\reports\ >nul
    echo   Copied sizing criteria TOML files
)

REM Copy JSON files from core/reports directory (e.g. units.json)
if exist pykorf\core\reports\*.json (
    if not exist %DIST_DIR%\pykorf\core\reports (
        mkdir %DIST_DIR%\pykorf\core\reports 2>nul
    )
    copy /y pykorf\core\reports\*.json %DIST_DIR%\pykorf\core\reports\ >nul
    echo   Copied report JSON files
)

REM Copy pyproject.toml
echo.
echo Copying pyproject.toml...
copy /y pyproject.toml %DIST_DIR%\pyproject.toml >nul
if errorlevel 1 (
    echo ERROR: Failed to copy pyproject.toml
    exit /b 1
)

REM Create VERSION file for version tracking
echo.
echo Creating VERSION file...
echo %VERSION%> %DIST_DIR%\VERSION

REM Extract BAT_VERSION from pykorf.bat for launcher version tracking
uv run python -c "import re;v=re.search(r'BAT_VERSION[=]([0-9.]+)',open('pykorf.bat').read()).group(1);open('dist/bat_version.txt','w').write(v)"

REM Copy standalone installer (must be inside zip for existing users)
if exist pykorf_installer.py (
    copy /y pykorf_installer.py %DIST_DIR%\ >nul
    echo   Copied pykorf_installer.py
) else (
    echo WARNING: pykorf_installer.py not found
)

REM Step 4: Create distribution zip
echo.
echo ==========================================
echo Step 4: Creating distribution package...
echo ==========================================
echo.
uv run python -c "import zipfile, os; z = zipfile.ZipFile(r'%DIST_DIR%/pykorf-latest.zip', 'w', zipfile.ZIP_DEFLATED); base = r'%DIST_DIR%'; [z.write(os.path.join(root, f), os.path.relpath(os.path.join(root, f), base)) for root, dirs, files in os.walk(base) for f in files if not f.endswith('.zip')]; z.close()"

REM Copy launcher batch script (after zip — kept as separate release asset, not inside zip)
echo.
echo Copying launcher...
copy /y pykorf.bat %DIST_DIR%\ >nul

REM Clean up unzipped content
REM Keep pykorf.bat — uploaded as separate release asset
echo Cleaning up...
for /d %%d in (%DIST_DIR%\*) do rd /s /q "%%d"
del /q %DIST_DIR%\pyproject.toml 2>nul

echo.
echo ==========================================
echo === Build Complete ===
echo ==========================================
echo Distribution package: %DIST_DIR%\pykorf-latest.zip
echo.
echo Contents:
echo   - pykorf/               (Python package + Vue dist assets)
echo   - pyproject.toml        (dependencies)
echo   - pykorf_installer.py   (standalone installer)
echo   - VERSION               (version tracker)
echo   - bat_version.txt       (launcher version)
echo.
echo Release assets:
echo   - pykorf-latest.zip     (distribution package)
echo   - pykorf.bat            (launcher - separate download)
echo.
echo Extract and run pykorf.bat to launch the web application.
